version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - sony-mathew
  - sojan-official
  - subintp
  labels:
  - dependencies
  - ruby
  ignore:
  - dependency-name: aws-sdk-s3
    versions:
    - 1.87.0
    - 1.88.0
    - 1.88.1
    - 1.90.0
    - 1.91.0
    - 1.92.0
    - 1.93.0
  - dependency-name: webmock
    versions:
    - 3.11.1
    - 3.11.2
    - 3.12.1
  - dependency-name: puma
    versions:
    - 5.1.1
    - 5.2.0
    - 5.2.1
  - dependency-name: brakeman
    versions:
    - 4.10.1
  - dependency-name: telegram-bot-ruby
    versions:
    - 0.14.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - pranavrajs
  - nithindavid
  labels:
  - dependencies
  - javascript
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: query-string
    versions:
    - 6.13.8
    - 6.14.0
    - 6.14.1
  - dependency-name: "@rails/actioncable"
    versions:
    - 6.1.1
    - 6.1.2
  - dependency-name: copy-text-to-clipboard
    versions:
    - 2.2.0
    - 3.0.0
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: expect-more-jest
    versions:
    - 5.2.1
